import DeleteAction from 'src/app/components/Actions/DeleteAction';
import EditAction from 'src/app/components/Actions/EditAction';
import ViewAction from 'src/app/components/Actions/ViewAction';
import ItemFormController from '../Form/ItemForm.controller';
import ItemViewController from '../View/ItemView.controller';

export const ItemAction = {
  COMMON_ACTION: {
    CREATE: {
      type: 'item',
      title: 'New Item',
      action: 'create',
      link: { to: '' },
      permission: 'auth:item:create',
      component: ItemFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    EDIT: {
      type: 'item',
      title: 'Edit Item',
      action: 'edit',
      link: { to: '' },
      permission: 'auth:item:edit',
      component: ItemFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'edit',
    },
    VIEW: {
      type: 'item',
      title: 'View Item',
      action: 'view',
      link: { to: '' },
      permission: 'auth:item:view',
      component: ItemViewController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'view',
    },
    DELETE: {
      type: 'item',
      title: 'Delete Item',
      action: 'delete',
      link: { to: '' },
      permission: 'auth:item:delete',
      component: '',
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
  },
  LIST_ITEM_ACTION: [
    {
      type: 'item',
      title: 'View',
      action: 'active',
      link: { to: '' },
      permission: 'auth:item:view',
      component: ViewAction,
      className: '',
      modalId: 'view',
      icon: 'information-4',
    },
    {
      type: 'item',
      title: 'Edit',
      action: 'inactive',
      link: { to: '' },
      permission: 'auth:item:edit',
      component: EditAction,
      className: '',
      modalId: 'edit',
      icon: 'pencil',
    },
    {
      type: 'item',
      title: 'Delete',
      action: 'delete',
      link: { to: '' },
      permission: 'auth:item:delete',
      component: DeleteAction,
      className: '',
      modalId: 'delete',
      icon: 'trash',
    },
  ],
  BULK_ACTION: {
    permission: 'auth:item:multiSelect',
    action_list: [
      {
        type: 'item',
        title: 'Mark as Active',
        action: 'active',
        link: { to: '' },
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Mark as Inactive',
        action: 'inactive',
        link: { to: '' },
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Delete',
        action: 'delete',
        link: { to: '' },
        permission: 'auth:item:delete',
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
    ],
  },
};
