export const LeftSidebarMenu = [
  {
    type: 'group',
    title: 'Root Menu',
    hidden: true,
    children: [
      {
        type: 'item',
        title: 'Dashboard',
        permission: '',
        link: {
          to: '/admin/dashboard',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'abstract-28',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Settings',
    hidden: false,
    children: [
      // COMPANY
      {
        type: 'item',
        title: 'Company',
        permission: 'auth:organization:menuAccess',
        link: { to: '/' },
        icon: 'people',
        subParent: true,
        subChildren: [
          {
            type: 'item',
            title: 'Users',
            permission: 'auth:user:menuAccess',
            link: {
              to: '/admin/setting/company/users',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Application Settings',
            permission: 'auth:applicationSetting:menuAccess',
            link: {
              to: '/admin/setting/company/application-settings',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Workflow Configuration',
            permission: 'auth:workflow:menuAccess',
            link: {
              to: '/admin/setting/company/workflow-configuration',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Workflow Approver Group',
            permission: 'auth:approverGroup:menuAccess',
            link: {
              to: '/admin/setting/company/approver-group',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Weekends and Holidays',
            permission: 'auth:govtHoliday:menuAccess',
            link: {
              to: '/admin/setting/company/govt-holiday',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Employees',
            permission: 'auth:employee:menuAccess',
            link: {
              to: '/admin/setting/company/employee',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
        ],
      },
      // PROFILE
      {
        type: 'item',
        title: 'Profile',
        permission: 'auth:example:menuAccess',
        link: { to: '/' },
        icon: 'setting-4',
        subParent: true,
        subChildren: [
          {
            type: 'item',
            title: 'Change Password',
            permission: 'auth:oauth:changePassword',
            link: {
              to: '/admin/setting/profile/change-password',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
        ],
      },
      // ROLE PERMISSIONS
      {
        type: 'item',
        title: 'Permissions',
        permission: 'auth:resource:menuAccess',
        link: { to: '/' },
        icon: 'lock-2',
        subParent: true,
        subChildren: [
          {
            type: 'item',
            title: 'Resource',
            permission: 'auth:resource:menuAccess',
            link: {
              to: '/admin/setting/permission/resource',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Scope',
            permission: 'auth:scope:menuAccess',
            link: {
              to: '/admin/setting/permission/scope',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Role',
            permission: 'auth:role:menuAccess',
            link: {
              to: '/admin/setting/permission/role',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Permissions',
            permission: 'auth:permission:rolePermission',
            link: {
              to: '/admin/setting/permission/permission-role',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
        ],
      },
      // SYSTEM
      {
        type: 'item',
        title: 'System',
        permission: 'auth:backup:menuAccess',
        link: { to: '/' },
        icon: 'setting-2',
        subParent: true,
        subChildren: [
          {
            type: 'item',
            title: 'Notification Templates',
            permission: 'auth:notification-template:menuAccess',
            link: {
              to: '/admin/setting/notification-template',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Database Backup',
            permission: 'auth:backup:menuAccess',
            link: {
              to: '/admin/setting/backup',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
        ],
      },
    ],
  },

  {
    type: 'group',
    title: 'Patient Management',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Patients',
        permission: 'auth:patient:menuAccess',
        link: { to: '/' },
        icon: 'people',
        subParent: true,
        subChildren: [
          {
            type: 'item',
            title: 'All Patients',
            permission: 'auth:patient:menuAccess',
            link: {
              to: '/admin/patient/list',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Merge Duplicates',
            permission: 'auth:patient:merge',
            link: {
              to: '/admin/patient/merge',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
        ],
      },
    ],
  },

  {
    type: 'group',
    title: 'Appointment Management',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Appointments',
        permission: 'auth:appointment:menuAccess',
        link: { to: '/' },
        icon: 'calendar',
        subParent: true,
        subChildren: [
          {
            type: 'item',
            title: 'All Appointments',
            permission: 'auth:appointment:menuAccess',
            link: {
              to: '/admin/appointment/list',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'New Appointment',
            permission: 'auth:appointment:create',
            link: {
              to: '/admin/appointment/create',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Walk-in',
            permission: 'auth:appointment:create',
            link: {
              to: '/admin/appointment/walk-in',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Queue Board',
            permission: 'auth:appointment:view',
            link: {
              to: '/admin/appointment/queue',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Doctor Schedules',
            permission: 'auth:doctor-schedule:menuAccess',
            link: {
              to: '/admin/appointment/schedules',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
        ],
      },
    ],
  },

  {
    type: 'group',
    title: 'OPD Management',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'OPD Visits',
        permission: 'auth:opd:menuAccess',
        link: { to: '/' },
        icon: 'medical-diagram',
        subParent: true,
        subChildren: [
          {
            type: 'item',
            title: 'All Visits',
            permission: 'auth:opd:list',
            link: {
              to: '/admin/opd/list',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'New Visit',
            permission: 'auth:opd:create',
            link: {
              to: '/admin/opd/create',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Today\'s Queue',
            permission: 'auth:opd:view',
            link: {
              to: '/admin/opd/queue',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Display Board',
            permission: 'auth:opd:list',
            link: {
              to: '/admin/opd/display-board',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Daily Collection Report',
            permission: 'auth:daily-collection-report:menuAccess',
            link: {
              to: '/admin/opd/report/daily-collection',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Diagnosis Templates',
            permission: 'auth:diagnosisTemplate:menuAccess',
            link: {
              to: '/admin/opd/diagnosis-templates',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'ICD-10 Codes',
            permission: 'auth:icd10Code:menuAccess',
            link: {
              to: '/admin/setup/icd10-code',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
        ],
      },
    ],
  },

  {
    type: 'group',
    title: 'Pharmacy',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Drug Master',
        permission: 'auth:drug:menuAccess',
        link: {
          to: '/admin/setup/drug',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'medicine',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Drug Expiry Report',
        permission: 'auth:drug-expiry-report:menuAccess',
        link: {
          to: '/admin/inventory/report/drug-expiry',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'calendar',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Drug Interactions',
        permission: 'auth:drugInteraction:menuAccess',
        link: {
          to: '/admin/setup/drug-interaction',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'shield-tick',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Controlled Drug Register',
        permission: 'auth:controlledDrugRegisterReport:menuAccess',
        link: {
          to: '/admin/inventory/report/controlled-drug-register',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'lock-2',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'IPD Management',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Bed Dashboard',
        permission: 'auth:bed:list',
        link: {
          to: '/admin/ipd/bed-dashboard',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'element-11',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Ward',
        permission: 'auth:ward:menuAccess',
        link: {
          to: '/admin/ipd/ward',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'home-3',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Bed',
        permission: 'auth:bed:menuAccess',
        link: {
          to: '/admin/ipd/bed',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'category',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Admission',
        permission: 'auth:ipd-admission:menuAccess',
        link: {
          to: '/admin/ipd/admission',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'hospital',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Emergency',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'ER Board',
        permission: 'auth:er-visit:list',
        link: {
          to: '/admin/emergency/board',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'flash-circle',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'ER Visits',
        permission: 'auth:er-visit:menuAccess',
        link: {
          to: '/admin/emergency/visit',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'ambulance',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Laboratory',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Lab Order Worklist',
        permission: 'auth:lab-order:menuAccess',
        link: {
          to: '/admin/lab/lab-order',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'flask',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Lab Test Catalog',
        permission: 'auth:lab-test:menuAccess',
        link: {
          to: '/admin/lab/lab-test',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'test-tube',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Radiology',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Radiology Order Worklist',
        permission: 'auth:radiology-order:menuAccess',
        link: {
          to: '/admin/radiology/radiology-order',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'scan-barcode',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Radiology Test Catalog',
        permission: 'auth:radiology-test:menuAccess',
        link: {
          to: '/admin/radiology/radiology-test',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'scan',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Report Templates',
        permission: 'auth:radiology-report-template:menuAccess',
        link: {
          to: '/admin/radiology/radiology-report-template',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'document',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Insurance & Billing',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Insurance Companies',
        permission: 'auth:insurance-company:menuAccess',
        link: {
          to: '/admin/insurance/insurance-company',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'shield-tick',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Pre-Authorization',
        permission: 'auth:pre-authorization:menuAccess',
        link: {
          to: '/admin/insurance/pre-authorization',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'document-add',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Billing Packages',
        permission: 'auth:billing-package:menuAccess',
        link: {
          to: '/admin/billing/billing-package',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'gift',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Insurance Claims',
        permission: 'auth:insurance-claim:menuAccess',
        link: {
          to: '/admin/insurance/claims',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'dollar',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Surgery & OT',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Theatres',
        permission: 'auth:theatre:menuAccess',
        link: {
          to: '/admin/ot/theatre',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'home-3',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'OT Bookings',
        permission: 'auth:ot-booking:menuAccess',
        link: {
          to: '/admin/ot/booking',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'calendar-8',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'HR',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'HR Masters',
        permission: 'auth:shift:menuAccess',
        link: {
          to: '/admin/hr/masters',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'setting-2',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Attendance',
        permission: 'auth:attendance-record:menuAccess',
        link: {
          to: '/admin/hr/attendance',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'time',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Leave Requests',
        permission: 'auth:leave-request:menuAccess',
        link: {
          to: '/admin/hr/leave-request',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'calendar-remove',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Leave Balance',
        permission: 'auth:leave-balance:list',
        link: {
          to: '/admin/hr/leave-balance',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'chart-pie-simple',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Doctor Portal',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Dashboard',
        permission: 'auth:doctorPortal:menuAccess',
        link: {
          to: '/admin/doctor/dashboard',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'element-11',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Daily Appointments',
        permission: 'auth:doctorPortal:menuAccess',
        link: {
          to: '/admin/doctor/daily-appointments',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'calendar-tick',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Prescription Templates',
        permission: 'auth:prescriptionTemplate:menuAccess',
        link: {
          to: '/admin/doctor/prescription-templates',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'document',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Procurement',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Purchase Orders',
        permission: 'auth:purchaseOrder:menuAccess',
        link: {
          to: '/admin/inventory/purchase-order',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'basket',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Purchase Order Approvals',
        permission: 'auth:purchaseOrderApproval:menuAccess',
        link: {
          to: '/admin/inventory/purchase-order-approval',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'check-square',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Vendor Comparison',
        permission: 'auth:vendorQuote:menuAccess',
        link: {
          to: '/admin/inventory/vendor-comparison',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'price-tag',
        subParent: false,
        subChildren: [],
      },
      {
        type: 'item',
        title: 'Rate Contracts',
        permission: 'auth:rateContract:menuAccess',
        link: {
          to: '/admin/inventory/rate-contract',
          exactMatch: true,
          externalUrl: false,
          openInNewTab: false,
        },
        icon: 'dollar',
        subParent: false,
        subChildren: [],
      },
    ],
  },

  {
    type: 'group',
    title: 'Back Office Setup',
    hidden: true,
    children: [
      {
        type: 'item',
        title: 'Back Office Setup',
        // permission: "auth:example:menuAccess",
        link: { to: '/' },
        icon: 'setting-2',
        subParent: true,
        subChildren: [
          // {
          //   type: 'item',
          //   title: 'DMP Unit',
          //   permission: 'auth:branch:menuAccess',
          //   link: {
          //     to: '/admin/setup/branch',
          //     exactMatch: true,
          //     externalUrl: false,
          //     openInNewTab: false,
          //   },
          // },
          {
            type: 'item',
            title: 'Department',
            permission: 'auth:department:menuAccess',
            link: {
              to: '/admin/setup/department',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Designation',
            permission: 'auth:designation:menuAccess',
            link: {
              to: '/admin/setup/designation',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Supplier',
            permission: 'auth:supplier:menuAccess',
            link: {
              to: '/admin/setup/supplier',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          // {
          //   type: 'item',
          //   title: 'Logistic',
          //   permission: 'auth:logistic:menuAccess',
          //   link: {
          //     to: '/admin/setup/logistic',
          //     exactMatch: true,
          //     externalUrl: false,
          //     openInNewTab: false,
          //   },
          // },
          // {
          //   type: 'item',
          //   title: 'Item Category',
          //   permission: 'auth:itemCategory:menuAccess',
          //   link: {
          //     to: '/admin/setup/item-category',
          //     exactMatch: true,
          //     externalUrl: false,
          //     openInNewTab: false,
          //   },
          // },
          // {
          //   type: 'item',
          //   title: 'Unit',
          //   permission: 'auth:unit:menuAccess',
          //   link: {
          //     to: '/admin/setup/unit',
          //     exactMatch: true,
          //     externalUrl: false,
          //     openInNewTab: false,
          //   },
          // },
          // {
          //   type: 'item',
          //   title: 'Brand',
          //   permission: 'auth:brand:menuAccess',
          //   link: {
          //     to: '/admin/setup/brand',
          //     exactMatch: true,
          //     externalUrl: false,
          //     openInNewTab: false,
          //   },
          // },
          // {
          //   type: 'item',
          //   title: 'Attribute',
          //   permission: 'auth:attribute:menuAccess',
          //   link: {
          //     to: '/admin/setup/attribute',
          //     exactMatch: true,
          //     externalUrl: false,
          //     openInNewTab: false,
          //   },
          // },
          // {
          //   type: 'item',
          //   title: 'Item',
          //   permission: 'auth:item:menuAccess',
          //   link: {
          //     to: '/admin/setup/item',
          //     exactMatch: true,
          //     externalUrl: false,
          //     openInNewTab: false,
          //   },
          // },
          // {
          //   type: 'item',
          //   title: 'Shelve',
          //   permission: 'auth:shelve:menuAccess',
          //   link: {
          //     to: '/admin/setup/shelve',
          //     exactMatch: true,
          //     externalUrl: false,
          //     openInNewTab: false,
          //   },
          // },
        ],
      },
    ],
  },

  {
    type: 'group',
    title: 'MIS & Analytics',
    hidden: false,
    children: [
      {
        type: 'item',
        title: 'Reports',
        link: { to: '/' },
        icon: 'chart-simple',
        subParent: true,
        subChildren: [
          {
            type: 'item',
            title: 'Executive Dashboard',
            permission: 'auth:mis-dashboard-report:menuAccess',
            link: {
              to: '/admin/report/mis-dashboard',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Occupancy & Revenue',
            permission: 'auth:occupancy-revenue-report:menuAccess',
            link: {
              to: '/admin/report/occupancy-revenue',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Doctor Productivity',
            permission: 'auth:doctor-productivity-report:menuAccess',
            link: {
              to: '/admin/report/doctor-productivity',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Pharmacy Sales Analytics',
            permission: 'auth:pharmacy-sales-analytics-report:menuAccess',
            link: {
              to: '/admin/report/pharmacy-sales-analytics',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Lab Revenue Analytics',
            permission: 'auth:lab-revenue-analytics-report:menuAccess',
            link: {
              to: '/admin/report/lab-revenue-analytics',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
          {
            type: 'item',
            title: 'Attendance Report',
            permission: 'auth:attendance-report:menuAccess',
            link: {
              to: '/admin/report/attendance',
              exactMatch: true,
              externalUrl: false,
              openInNewTab: false,
            },
          },
        ],
      },
    ],
  },

  // {
  //   type: 'group',
  //   title: 'Inventory',
  //   hidden: false,
  //   children: [
  //     {
  //       type: 'item',
  //       title: 'Requisition',
  //       permission: 'auth:requisition:menuAccess',
  //       link: {
  //         to: '/admin/inventory/requisition',
  //         exactMatch: true,
  //         externalUrl: false,
  //         openInNewTab: false,
  //       },
  //       icon: 'abstract-28',
  //       subParent: false,
  //       subChildren: [],
  //     },
  //     {
  //       type: 'item',
  //       title: 'Goods Receive Note',
  //       permission: 'auth:goodsReceiveNote:menuAccess',
  //       link: {
  //         to: '/admin/inventory/goods-receive-note',
  //         exactMatch: true,
  //         externalUrl: false,
  //         openInNewTab: false,
  //       },
  //       icon: 'abstract-28',
  //       subParent: false,
  //       subChildren: [],
  //     },
  //     {
  //       type: 'item',
  //       title: 'Stock Adjustment',
  //       permission: 'auth:stock-adjustment:menuAccess',
  //       link: {
  //         to: '/admin/inventory/stock-adjustment',
  //         exactMatch: true,
  //         externalUrl: false,
  //         openInNewTab: false,
  //       },
  //       icon: 'abstract-28',
  //       subParent: false,
  //       subChildren: [],
  //     },
  //     {
  //       type: 'item',
  //       title: 'Item Consumption',
  //       permission: 'auth:itemConsumption:menuAccess',
  //       link: {
  //         to: '/admin/inventory/item-consumption',
  //         exactMatch: true,
  //         externalUrl: false,
  //         openInNewTab: false,
  //       },
  //       icon: 'abstract-28',
  //       subParent: false,
  //       subChildren: [],
  //     },
  //     {
  //       type: 'item',
  //       title: 'Stock Transfer',
  //       permission: 'auth:stockTransfer:menuAccess',
  //       link: {
  //         to: '/admin/inventory/stock-transfer',
  //         exactMatch: true,
  //         externalUrl: false,
  //         openInNewTab: false,
  //       },
  //       icon: 'abstract-28',
  //       subParent: false,
  //       subChildren: [],
  //     },

  //     {
  //       type: 'item',
  //       title: 'Approvals',
  //       link: { to: '/' },
  //       icon: 'double-down',
  //       subParent: true,
  //       subChildren: [
  //         {
  //           type: 'item',
  //           title: 'Requisition Approval',
  //           permission: 'auth:requisitionApproval:menuAccess',
  //           link: {
  //             to: '/admin/inventory/requisition-approval',
  //             exactMatch: true,
  //             externalUrl: false,
  //             openInNewTab: false,
  //           },
  //         },
  //         {
  //           type: 'item',
  //           title: 'Goods Receive Note Approval',
  //           permission: 'auth:goodsReceiveNoteApproval:menuAccess',
  //           link: {
  //             to: '/admin/inventory/goods-receive-note-approval',
  //             exactMatch: true,
  //             externalUrl: false,
  //             openInNewTab: false,
  //           },
  //         },
  //         {
  //           type: 'item',
  //           title: 'Stock Adjustment Approval',
  //           permission: 'auth:stockAdjustmentApproval:menuAccess',
  //           link: {
  //             to: '/admin/inventory/stock-adjustment-approval',
  //             exactMatch: true,
  //             externalUrl: false,
  //             openInNewTab: false,
  //           },
  //         },
  //         {
  //           type: 'item',
  //           title: 'Stock Transfer Approval',
  //           permission: 'auth:stockTransferApproval:menuAccess',
  //           link: {
  //             to: '/admin/inventory/stock-transfer-approval',
  //             exactMatch: true,
  //             externalUrl: false,
  //             openInNewTab: false,
  //           },
  //         },
  //       ],
  //     },
  //     // REPORTS
  //     {
  //       type: 'item',
  //       title: 'Reports',
  //       link: { to: '/' },
  //       icon: 'double-down',
  //       subParent: true,
  //       subChildren: [
  //         {
  //           type: 'item',
  //           title: 'Item Stock Analytics',
  //           permission: 'auth:item-stock-analytics-report:menuAccess',
  //           link: {
  //             to: '/admin/inventory/report/item-stock',
  //             exactMatch: true,
  //             externalUrl: false,
  //             openInNewTab: false,
  //           },
  //         },
  //         {
  //           type: 'item',
  //           title: 'Requisition Analytics',
  //           permission: 'auth:requisition-analytics-report:menuAccess',
  //           link: {
  //             to: '/admin/inventory/report/requisition-analytics',
  //             exactMatch: true,
  //             externalUrl: false,
  //             openInNewTab: false,
  //           },
  //         },
  //         // {
  //         //   type: 'item',
  //         //   title: 'Demand vs Stock',
  //         //   permission: 'auth:item-low-stock-report:menuAccess',
  //         //   link: {
  //         //     to: '/admin/inventory/report/item-low-stock',
  //         //     exactMatch: true,
  //         //     externalUrl: false,
  //         //     openInNewTab: false,
  //         //   },
  //         // },
  //         {
  //           type: 'item',
  //           title: 'Unit Wise Requisition Statistics',
  //           permission:
  //             'auth:unit-wise-requisition-statistics-report:menuAccess',
  //           link: {
  //             to: '/admin/inventory/report/requisition-statistics',
  //             exactMatch: true,
  //             externalUrl: false,
  //             openInNewTab: false,
  //           },
  //         },
  //         {
  //           type: 'item',
  //           title: 'Disbursement Analytics',
  //           permission: '',
  //           link: { to: '/' },
  //           icon: 'people',
  //           subParent: true,
  //           subChildren: [
  //             {
  //               type: 'item',
  //               title: 'Requester Wise',
  //               permission:
  //                 'auth:requester-wise-disbursement-report:menuAccess',
  //               link: {
  //                 to: '/admin/inventory/report/requester-wise-disbursement',
  //                 exactMatch: true,
  //                 externalUrl: false,
  //                 openInNewTab: false,
  //               },
  //             },
  //             {
  //               type: 'item',
  //               title: 'DMP Unit Wise',
  //               permission: 'auth:branch-wise-disbursement-report:menuAccess',
  //               link: {
  //                 to: '/admin/inventory/report/branch-wise-disbursement',
  //                 exactMatch: true,
  //                 externalUrl: false,
  //                 openInNewTab: false,
  //               },
  //             },
  //             {
  //               type: 'item',
  //               title: 'Item Wise',
  //               permission: 'auth:item-wise-disbursement-report:menuAccess',
  //               link: {
  //                 to: '/admin/inventory/report/item-wise-disbursement',
  //                 exactMatch: true,
  //                 externalUrl: false,
  //                 openInNewTab: false,
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  // },
];
