export enum RequisitionProcessStatusEnum {
  NEW_REQUISITION = 'NEW_REQUISITION',
  HOD_REVIEWED = 'HOD_REVIEWED',
  HOD_REJECTED = 'HOD_REJECTED',
  STOCK_CHECKED = 'STOCK_CHECKED',
  STOCK_CHECK_REJECTED = 'STOCK_CHECK_REJECTED',
  SCM_HEAD_APPROVED = 'SCM_HEAD_APPROVED',
  SCM_HEAD_REJECTED = 'SCM_HEAD_REJECTED',
  CEO_REJECTED = 'CEO_REJECTED',
  FINAL_APPROVED = 'FINAL_APPROVED',
}

export enum CSProcessStatusEnum {
  NEW_CS = 'NEW_CS',
  SCM_HEAD_APPROVED = 'SCM_HEAD_APPROVED',
  SCM_HEAD_REJECTED = 'SCM_HEAD_REJECTED',
  CEO_REJECTED = 'CEO_REJECTED',
  FINAL_APPROVED = 'FINAL_APPROVED',
}

export enum POProcessStatusEnum {
  NEW_PO = 'NEW_PO',
  SCM_HEAD_APPROVED = 'SCM_HEAD_APPROVED',
  SCM_HEAD_REJECTED = 'SCM_HEAD_REJECTED',
  CEO_REJECTED = 'CEO_REJECTED',
  FINAL_APPROVED = 'FINAL_APPROVED',
  CLOSED = 'CLOSED',
}

export enum PTProcessStatusEnum {
  NEW_PO = 'NEW_TRP',
  HOD_REVIEWED = 'HOD_REVIEWED',
  HOD_RECHECK = 'HOD_RECHECK',
  HOD_REJECTED = 'HOD_REJECTED',
  IN_TRANSIT = 'IN_TRANSIT',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
}

export enum MTProcessStatusEnum {
  NEW_PO = 'NEW_MATERIAL_RETURN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
}

export enum SRProcessStatusEnum {
  NEW_PO = 'NEW_SALES_RETURN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
}

export enum SAProcessStatusEnum {
  NEW_PO = 'NEW_ADJUSTMENT',
  SCM_HEAD_APPROVED = 'SCM_HEAD_APPROVED',
  SCM_HEAD_REJECTED = 'SCM_HEAD_REJECTED',
  CEO_APPROVED = 'CEO_APPROVED',
  CEO_REJECTED = 'CEO_REJECTED',
}
