import DeleteAction from 'src/app/components/Actions/DeleteAction'
import EditAction from 'src/app/components/Actions/EditAction'
import ViewAction from 'src/app/components/Actions/ViewAction'
import ExampleFormController from '../Form/ExampleForm.controller'
import ExampleViewController from '../View/ExampleView.controller'

export const ExampleAction = {
  COMMON_ACTION: {
    CREATE: {
      type: 'item',
      title: 'New Example',
      action: 'create',
      link: {to: ''},
      permission: 'auth:example:create',
      component: ExampleFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    EDIT: {
      type: 'item',
      title: 'Edit Example',
      action: 'edit',
      link: {to: ''},
      permission: 'auth:example:edit',
      component: ExampleFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'edit',
    },
    VIEW: {
      type: 'item',
      title: 'View Example',
      action: 'view',
      link: {to: ''},
      permission: 'auth:example:view',
      component: ExampleViewController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'view',
    },
    DELETE: {
      type: 'item',
      title: 'Delete Example',
      action: 'delete',
      link: {to: ''},
      permission: 'auth:example:delete',
      component: '',
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
  },
  LIST_ITEM_ACTION: [
    {
      type: 'item',
      title: 'View',
      action: 'active',
      link: {to: ''},
      permission: 'auth:example:view',
      component: ViewAction,
      className: '',
      modalId: 'view',
      icon: 'information-4',
    },
    {
      type: 'item',
      title: 'Edit',
      action: 'inactive',
      link: {to: ''},
      permission: 'auth:example:edit',
      component: EditAction,
      className: '',
      modalId: 'edit',
      icon: 'pencil',
    },
    {
      type: 'item',
      title: 'Delete',
      action: 'delete',
      link: {to: ''},
      permission: 'auth:example:delete',
      component: DeleteAction,
      className: '',
      modalId: 'delete',
      icon: 'trash',
    },
  ],
  BULK_ACTION: {
    permission: 'auth:example:multiSelect',
    action_list: [
      {
        type: 'item',
        title: 'Mark as Active',
        action: 'active',
        link: {to: ''},
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Mark as Inactive',
        action: 'inactive',
        link: {to: ''},
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Delete',
        action: 'delete',
        link: {to: ''},
        permission: 'auth:example:delete',
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
    ],
  },
}
