import DeleteAction from 'src/app/components/Actions/DeleteAction'
import EditAction from 'src/app/components/Actions/EditAction'
import ViewAction from 'src/app/components/Actions/ViewAction'
import GoodsReceiveNoteFormController from '../Form/GoodsReceiveNoteForm.controller'
import GoodsReceiveNoteViewController from '../View/GoodsReceiveNoteView.controller'

export const GoodsReceiveNoteAction = {
  COMMON_ACTION: {
    CREATE: {
      type: 'item',
      title: 'New Goods Receive Note',
      action: 'create',
      link: {to: ''},
      permission: 'auth:goodsReceiveNote:create',
      component: GoodsReceiveNoteFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    EDIT: {
      type: 'item',
      title: 'Edit Goods Receive Note',
      action: 'edit',
      link: {to: ''},
      permission: 'auth:goodsReceiveNote:edit',
      component: GoodsReceiveNoteFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'edit',
    },
    VIEW: {
      type: 'item',
      title: 'View Goods Receive Note',
      action: 'view',
      link: {to: ''},
      permission: 'auth:goodsReceiveNote:view',
      component: GoodsReceiveNoteViewController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'view',
    },
    DELETE: {
      type: 'item',
      title: 'Delete Goods Receive Note',
      action: 'delete',
      link: {to: ''},
      permission: 'auth:goodsReceiveNote:delete',
      component: '',
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
  },
  LIST_ITEM_ACTION: [
    {
      type: 'item',
      title: 'View',
      action: 'active',
      link: {to: ''},
      permission: 'auth:goodsReceiveNote:view',
      component: ViewAction,
      className: '',
      modalId: 'view',
      icon: 'information-4',
    },
    {
      type: 'item',
      title: 'Edit',
      action: 'inactive',
      link: {to: ''},
      permission: 'auth:goodsReceiveNote:edit',
      component: EditAction,
      className: '',
      modalId: 'edit',
      icon: 'pencil',
    },
    {
      type: 'item',
      title: 'Delete',
      action: 'delete',
      link: {to: ''},
      permission: 'auth:goodsReceiveNote:delete',
      component: DeleteAction,
      className: '',
      modalId: 'delete',
      icon: 'trash',
    },
  ],
  BULK_ACTION: {
    permission: 'auth:goodsReceiveNote:multiSelect',
    action_list: [
      {
        type: 'item',
        title: 'Mark as Active',
        action: 'active',
        link: {to: ''},
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Mark as Inactive',
        action: 'inactive',
        link: {to: ''},
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Delete',
        action: 'delete',
        link: {to: ''},
        permission: 'auth:goodsReceiveNote:delete',
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
    ],
  },
}
