import DeleteAction from 'src/app/components/Actions/DeleteAction'
import EditAction from 'src/app/components/Actions/EditAction'
import ViewAction from 'src/app/components/Actions/ViewAction'
import StockAdjustmentFormController from '../Form/StockAdjustmentForm.controller'
import StockAdjustmentViewController from '../View/StockAdjustmentView.controller'

export const StockAdjustmentAction = {
  COMMON_ACTION: {
    CREATE: {
      type: 'item',
      title: 'New Stock Adjustment',
      action: 'create',
      link: {to: ''},
      permission: 'auth:stock-adjustment:create',
      component: StockAdjustmentFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    EDIT: {
      type: 'item',
      title: 'Edit Stock Adjustment',
      action: 'edit',
      link: {to: ''},
      permission: 'auth:stock-adjustment:edit',
      component: StockAdjustmentFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'edit',
    },
    VIEW: {
      type: 'item',
      title: 'View Stock Adjustment',
      action: 'view',
      link: {to: ''},
      permission: 'auth:stock-adjustment:view',
      component: StockAdjustmentViewController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'view',
    },
    DELETE: {
      type: 'item',
      title: 'Delete Stock Adjustment',
      action: 'delete',
      link: {to: ''},
      permission: 'auth:stock-adjustment:delete',
      component: '',
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    REQUEST_ACKNOWLEDGEMENT: {
      type: 'item',
      title: 'Request Acknowledgement',
      action: 'edit',
      link: {to: ''},
      permission: 'auth:stock-adjustment:requestAcknowledgement',
      component: '',
      className: 'grid-view-action',
    },
  },
  LIST_ITEM_ACTION: [
    {
      type: 'item',
      title: 'View',
      action: 'active',
      link: {to: ''},
      permission: 'auth:stock-adjustment:view',
      component: ViewAction,
      className: '',
      modalId: 'view',
      icon: 'information-4',
    },
    {
      type: 'item',
      title: 'Edit',
      action: 'inactive',
      link: {to: ''},
      permission: 'auth:stock-adjustment:edit',
      component: EditAction,
      className: '',
      modalId: 'edit',
      icon: 'pencil',
    },
    {
      type: 'item',
      title: 'Delete',
      action: 'delete',
      link: {to: ''},
      permission: 'auth:stock-adjustment:delete',
      component: DeleteAction,
      className: '',
      modalId: 'delete',
      icon: 'trash',
    },
  ],
  BULK_ACTION: {
    permission: 'auth:stock-adjustment:multiSelect',
    action_list: [
      {
        type: 'item',
        title: 'Mark as Active',
        action: 'active',
        link: {to: ''},
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Mark as Inactive',
        action: 'inactive',
        link: {to: ''},
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Delete',
        action: 'delete',
        link: {to: ''},
        permission: 'auth:stock-adjustment:delete',
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
    ],
  },
}
