import DeleteAction from '../../../../../components/Actions/DeleteAction';
import EditAction from '../../../../../components/Actions/EditAction';
import ViewAction from '../../../../../components/Actions/ViewAction';
import ApproverGroupFormController from '../Form/ApproverGroupForm.controller';
import ApproverGroupViewController from '../View/ApproverGroupView.controller';

export const ApproverGroupAction = {
  COMMON_ACTION: {
    CREATE: {
      type: 'item',
      title: 'New Approver Group',
      action: 'create',
      link: { to: '' },
      permission: 'auth:approverGroup:create',
      component: ApproverGroupFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    EDIT: {
      type: 'item',
      title: 'Edit Approver Group',
      action: 'edit',
      link: { to: '' },
      permission: 'auth:approverGroup:edit',
      component: ApproverGroupFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'edit',
    },
    VIEW: {
      type: 'item',
      title: 'View Approver Group',
      action: 'view',
      link: { to: '' },
      permission: 'auth:approverGroup:view',
      component: ApproverGroupViewController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'view',
    },
    DELETE: {
      type: 'item',
      title: 'Delete Approver Group',
      action: 'delete',
      link: { to: '' },
      permission: 'auth:approverGroup:delete',
      component: '',
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
  },
  LIST_ITEM_ACTION: [
    {
      type: 'item',
      title: 'View',
      action: 'active',
      link: { to: '' },
      permission: 'auth:approverGroup:view',
      component: ViewAction,
      className: '',
      modalId: 'view',
      icon: 'information-4',
    },
    {
      type: 'item',
      title: 'Edit',
      action: 'inactive',
      link: { to: '' },
      permission: 'auth:approverGroup:edit',
      component: EditAction,
      className: '',
      modalId: 'edit',
      icon: 'pencil',
    },
    {
      type: 'item',
      title: 'Delete',
      action: 'delete',
      link: { to: '' },
      permission: 'auth:approverGroup:delete',
      component: DeleteAction,
      className: '',
      modalId: 'delete',
      icon: 'trash',
    },
  ],
  BULK_ACTION: {
    permission: 'auth:approverGroup:multiSelect',
    action_list: [
      {
        type: 'item',
        title: 'Mark as Active',
        action: 'active',
        link: { to: '' },
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Mark as Inactive',
        action: 'inactive',
        link: { to: '' },
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Delete',
        action: 'delete',
        link: { to: '' },
        permission: 'auth:approverGroup:delete',
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
    ],
  },
};
