import DeleteAction from 'src/app/components/Actions/DeleteAction';
import EditAction from 'src/app/components/Actions/EditAction';
import ViewAction from 'src/app/components/Actions/ViewAction';
import GovtHolidayFormController from '../Form/GovtHolidayForm.controller';
import GovtHolidayViewController from '../View/GovtHolidayView.controller';

export const GovtHolidayAction = {
  COMMON_ACTION: {
    CREATE: {
      type: 'item',
      title: 'New Weekend and Holiday',
      action: 'create',
      link: { to: '' },
      permission: 'auth:govtHoliday:create',
      component: GovtHolidayFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    EDIT: {
      type: 'item',
      title: 'Edit Weekend and Holiday',
      action: 'edit',
      link: { to: '' },
      permission: 'auth:govtHoliday:edit',
      component: GovtHolidayFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'edit',
    },
    VIEW: {
      type: 'item',
      title: 'View Weekend and Holiday',
      action: 'view',
      link: { to: '' },
      permission: 'auth:govtHoliday:view',
      component: GovtHolidayViewController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'view',
    },
    DELETE: {
      type: 'item',
      title: 'Delete Weekend and Holiday',
      action: 'delete',
      link: { to: '' },
      permission: 'auth:govtHoliday:delete',
      component: '',
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
  },
  LIST_ITEM_ACTION: [
    {
      type: 'item',
      title: 'View',
      action: 'active',
      link: { to: '' },
      permission: 'auth:govtHoliday:view',
      component: ViewAction,
      className: '',
      modalId: 'view',
      icon: 'information-4',
    },
    {
      type: 'item',
      title: 'Edit',
      action: 'inactive',
      link: { to: '' },
      permission: 'auth:govtHoliday:edit',
      component: EditAction,
      className: '',
      modalId: 'edit',
      icon: 'pencil',
    },
    {
      type: 'item',
      title: 'Delete',
      action: 'delete',
      link: { to: '' },
      permission: 'auth:govtHoliday:delete',
      component: DeleteAction,
      className: '',
      modalId: 'delete',
      icon: 'trash',
    },
  ],
  BULK_ACTION: {
    permission: 'auth:govtHoliday:multiSelect',
    action_list: [
      {
        type: 'item',
        title: 'Mark as Active',
        action: 'active',
        link: { to: '' },
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Mark as Inactive',
        action: 'inactive',
        link: { to: '' },
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Delete',
        action: 'delete',
        link: { to: '' },
        permission: 'auth:govtHoliday:delete',
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
    ],
  },
};
