import DeleteAction from 'src/app/components/Actions/DeleteAction'
import EditAction from 'src/app/components/Actions/EditAction'
import ViewAction from 'src/app/components/Actions/ViewAction'
import RequisitionFormController from '../Form/RequisitionForm.controller'
import RequisitionViewController from '../View/RequisitionView.controller'

export const RequisitionAction = {
  COMMON_ACTION: {
    CREATE: {
      type: 'item',
      title: 'New Requisition',
      action: 'create',
      link: {to: ''},
      permission: 'auth:requisition:create',
      component: RequisitionFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    EDIT: {
      type: 'item',
      title: 'Edit Requisition',
      action: 'edit',
      link: {to: ''},
      permission: 'auth:requisition:edit',
      component: RequisitionFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'edit',
    },
    VIEW: {
      type: 'item',
      title: 'View Requisition',
      action: 'view',
      link: {to: ''},
      permission: 'auth:requisition:view',
      component: RequisitionViewController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'view',
    },
    DELETE: {
      type: 'item',
      title: 'Delete Requisition',
      action: 'delete',
      link: {to: ''},
      permission: 'auth:requisition:delete',
      component: '',
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    REQUEST_ACKNOWLEDGEMENT: {
      type: 'item',
      title: 'Request Acknowledgement',
      action: 'edit',
      link: {to: ''},
      permission: 'auth:requisition:requestAcknowledgement',
      component: '',
      className: 'grid-view-action',
    },
  },
  LIST_ITEM_ACTION: [
    {
      type: 'item',
      title: 'View',
      action: 'active',
      link: {to: ''},
      permission: 'auth:requisition:view',
      component: ViewAction,
      className: '',
      modalId: 'view',
      icon: 'information-4',
    },
    {
      type: 'item',
      title: 'Edit',
      action: 'inactive',
      link: {to: ''},
      permission: 'auth:requisition:edit',
      component: EditAction,
      className: '',
      modalId: 'edit',
      icon: 'pencil',
    },
    {
      type: 'item',
      title: 'Delete',
      action: 'delete',
      link: {to: ''},
      permission: 'auth:requisition:delete',
      component: DeleteAction,
      className: '',
      modalId: 'delete',
      icon: 'trash',
    },
  ],
  BULK_ACTION: {
    permission: 'auth:requisition:multiSelect',
    action_list: [
      {
        type: 'item',
        title: 'Mark as Active',
        action: 'active',
        link: {to: ''},
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Mark as Inactive',
        action: 'inactive',
        link: {to: ''},
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Delete',
        action: 'delete',
        link: {to: ''},
        permission: 'auth:requisition:delete',
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
    ],
  },
}
