import ViewAction from 'src/app/components/Actions/ViewAction';
import AttributeFormController from '../Form/AttributeForm.controller';
import AttributeViewController from '../View/AttributeView.controller';
import DeleteAction from 'src/app/components/Actions/DeleteAction';
import EditAction from 'src/app/components/Actions/EditAction';

export const AttributeAction = {
  COMMON_ACTION: {
    CREATE: {
      type: 'item',
      title: 'New Attribute',
      action: 'create',
      link: { to: '' },
      permission: 'auth:attribute:create',
      component: AttributeFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
    EDIT: {
      type: 'item',
      title: 'Edit Attribute',
      action: 'edit',
      link: { to: '' },
      permission: 'auth:attribute:edit',
      component: AttributeFormController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'edit',
    },
    VIEW: {
      type: 'item',
      title: 'View Attribute',
      action: 'view',
      link: { to: '' },
      permission: 'auth:attribute:view',
      component: AttributeViewController,
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
      modalId: 'view',
    },
    DELETE: {
      type: 'item',
      title: 'Delete Attribute',
      action: 'delete',
      link: { to: '' },
      permission: 'auth:attribute:delete',
      component: '',
      className: 'grid-view-action',
      // icon: <EyeOutlined />,
    },
  },
  LIST_ITEM_ACTION: [
    {
      type: 'item',
      title: 'View',
      action: 'active',
      link: { to: '' },
      permission: 'auth:attribute:view',
      component: ViewAction,
      className: '',
      modalId: 'view',
      icon: 'information-4',
    },
    {
      type: 'item',
      title: 'Edit',
      action: 'inactive',
      link: { to: '' },
      permission: 'auth:attribute:edit',
      component: EditAction,
      className: '',
      modalId: 'edit',
      icon: 'pencil',
    },
    {
      type: 'item',
      title: 'Delete',
      action: 'delete',
      link: { to: '' },
      permission: 'auth:attribute:delete',
      component: DeleteAction,
      className: '',
      modalId: 'delete',
      icon: 'trash',
    },
  ],
  BULK_ACTION: {
    permission: 'auth:attribute:multiSelect',
    action_list: [
      {
        type: 'item',
        title: 'Mark as Active',
        action: 'active',
        link: { to: '' },
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Mark as Inactive',
        action: 'inactive',
        link: { to: '' },
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
      {
        type: 'item',
        title: 'Delete',
        action: 'delete',
        link: { to: '' },
        permission: 'auth:attribute:delete',
        component: '',
        className: 'grid-view-action',
        // icon: <EyeOutlined />,
      },
    ],
  },
};
